/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthIndexImport } from './routes/_auth.index'
import { Route as AuthGuildsImport } from './routes/_auth.guilds'
import { Route as AuthGuildsIndexImport } from './routes/_auth.guilds.index'
import { Route as AuthGuildsGuildIdImport } from './routes/_auth.guilds.$guildId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthGuildsRoute = AuthGuildsImport.update({
  path: '/guilds',
  getParentRoute: () => AuthRoute,
} as any)

const AuthGuildsIndexRoute = AuthGuildsIndexImport.update({
  path: '/',
  getParentRoute: () => AuthGuildsRoute,
} as any)

const AuthGuildsGuildIdRoute = AuthGuildsGuildIdImport.update({
  path: '/$guildId',
  getParentRoute: () => AuthGuildsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_auth/guilds': {
      id: '/_auth/guilds'
      path: '/guilds'
      fullPath: '/guilds'
      preLoaderRoute: typeof AuthGuildsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/guilds/$guildId': {
      id: '/_auth/guilds/$guildId'
      path: '/$guildId'
      fullPath: '/guilds/$guildId'
      preLoaderRoute: typeof AuthGuildsGuildIdImport
      parentRoute: typeof AuthGuildsImport
    }
    '/_auth/guilds/': {
      id: '/_auth/guilds/'
      path: '/'
      fullPath: '/guilds/'
      preLoaderRoute: typeof AuthGuildsIndexImport
      parentRoute: typeof AuthGuildsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthRoute: AuthRoute.addChildren({
    AuthGuildsRoute: AuthGuildsRoute.addChildren({
      AuthGuildsGuildIdRoute,
      AuthGuildsIndexRoute,
    }),
    AuthIndexRoute,
  }),
  LoginRoute,
  SignupRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login",
        "/signup"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/guilds",
        "/_auth/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_auth/guilds": {
      "filePath": "_auth.guilds.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/guilds/$guildId",
        "/_auth/guilds/"
      ]
    },
    "/_auth/": {
      "filePath": "_auth.index.tsx",
      "parent": "/_auth"
    },
    "/_auth/guilds/$guildId": {
      "filePath": "_auth.guilds.$guildId.tsx",
      "parent": "/_auth/guilds"
    },
    "/_auth/guilds/": {
      "filePath": "_auth.guilds.index.tsx",
      "parent": "/_auth/guilds"
    }
  }
}
ROUTE_MANIFEST_END */
